#A tutorial book is provided when players enter the world for the first time
provideTutorialBooks = true
#After being turned off, the Cocoa Manin effect will not remove the invincibility frame of the creatures
cocoaManinDamageEffect = true
#The baking speed of Toaster compared to Campfire
#Range: 1.0 ~ 30.0
toasterDoubleSpeed = 3.0
#After disabling this option, there will be no April Fool's Day effect.
aprilFoolsDayEffect = true
#Enjoy effect increases the damage dealt by Eternal Baguette
#Range: 0.0 ~ 1.7976931348623157E308
eternalBaguetteDamageUp = 2.0

